export const localImages = {
  titleScreen: '/custom-images/logo.png',
  profilePhoto: '/custom-images/welcome/boy.png',
  welcomeBoy: '/custom-images/welcome/boy.png',
  welcomeGirl: '/custom-images/welcome/girl.png',
};

export const remoteImages = {
  wakeUp: '/custom-images/tasks/wake-up.png',
  brushTeeth: '/custom-images/tasks/brush-teeth.png',
  getDressed: '/custom-images/tasks/get-dressed.png',
  eatBreakfast: '/custom-images/tasks/eat-breakfast.png',
  goToSchool: '/custom-images/tasks/go-to-school.png',
  arriveSchool: '/custom-images/tasks/arrive-school.png',
  morningCircle: '/custom-images/tasks/morning-circle.png',
  classwork: '/custom-images/tasks/classwork.png',
  schoolSnack: '/custom-images/tasks/school-snack.png',
  recess: '/custom-images/tasks/recess.png',
  afternoonLessons: '/custom-images/tasks/afternoon-lessons.png',
  packUpSchool: '/custom-images/tasks/pack-up-school.png',
  washHands: '/custom-images/tasks/wash-hands.png',
  eatLunch: '/custom-images/tasks/eat-lunch.png',
  doHomework: '/custom-images/tasks/do-homework.png',
  packSnack: '/custom-images/tasks/pack-snack.png',
  playTime: '/custom-images/tasks/play-time.png',
  putPlateSink: '/custom-images/tasks/put-plate-sink.png',
  putToysAway: '/custom-images/tasks/put-toys-away.png',
  makeBed: '/custom-images/tasks/make-bed.png',
  feedPet: '/custom-images/tasks/feed-pet.png',
  waterPlants: '/custom-images/tasks/water-plants.png',
  putClothesHamper: '/custom-images/tasks/put-clothes-hamper.png',
  helpSetTable: '/custom-images/tasks/help-set-table.png',
  eatDinner: '/custom-images/tasks/eat-dinner.png',
  bathTime: '/custom-images/tasks/bath-time.png',
  readBook: '/custom-images/tasks/read-book.png',
  bedtime: '/custom-images/tasks/bedtime.png',
  speechTherapy: '/custom-images/tasks/speech-therapy.png',
  occupationalTherapy: '/custom-images/tasks/occupational-therapy.png',
  physicalTherapy: '/custom-images/tasks/physical-therapy.png',
  behavioralTherapy: '/custom-images/tasks/behavioral-therapy.png',
  sensoryTherapy: '/custom-images/tasks/sensory-therapy.png',
  feelUnwell: '/custom-images/tasks/feel-unwell.png',
  tellAdult: '/custom-images/tasks/tell-adult.png',
  takeTemperature: '/custom-images/tasks/take-temperature.png',
  restInBed: '/custom-images/tasks/rest-in-bed.png',
  takeMedicine: '/custom-images/tasks/take-medicine.png',
  drinkWater: '/custom-images/tasks/drink-water.png',
  goToDoctor: '/custom-images/tasks/go-to-doctor.png',
  emotionCheck: '/custom-images/tasks/emotion-check.png',
};
